matrix:
  include:

    - dist: xenial
      language: python
      python: "3.7"

      install:
        - pip3 install pylint mypy tox-travis

      script:
        - make -C py lint
        - make -C py test

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF py
