matrix:
  include:

    - language: node_js
      node_js: "10"

      script:
        - npm run lint
        - npm run build
        - npm run test
        - npm run docs

      deploy:
        # Deploy a new version of NPM package and create a Github release
        - provider: script
          skip_cleanup: true
          script: npx semantic-release

        # Deploy documentation to Github Pages
        # See https://docs.travis-ci.com/user/deployment/pages/
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: built
          on:
            branch: master

    - dist: xenial
      language: python
      python: "3.7"

      install:
        - pip3 install pylint mypy tox-travis

      script:
        - make lint-py
        - make test-py

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF py

    - language: r
      r: release

      install:
        - make setup

      script:
        - make lint-r
        - make test-r
        - make build-r

      after_success:
        - Rscript -e "covr::codecov()"
