matrix:
  include:

    - language: r
      r: release

      install:
        - make -C r setup

      script:
        - make -C r lint
        - make -C r test
        - make -C r build

      after_success:
        - make -C r cover
        - bash <(curl -s https://codecov.io/bash) -cF r
