jobs:
  include:
    - stage: test
      language: node_js
      node_js: '10'

      script:
        - npm run lint
        - npm run build
        - npm run test
        - npm run docs

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF ts

    - stage: test
      language: python
      python: '3.7'
      dist: xenial

      install:
        - make -C py setup

      script:
        - make -C py lint
        - make -C py test

      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF py

    - stage: test
      language: r
      r: release
      dist: xenial
      sudo: true

      r_binary_packages:
        - covr
        - roxygen2
        - testthat

      r_github_packages:
        - jimhester/lintr

      before_install:
        - cd r

      script:
        - make lint
        - make test
        - make build

      after_success:
        - Rscript -e 'covr::codecov()'

    # The following deployment jobs will only run if all of
    # the above test jobs have passed

    - stage: deploy
      language: node_js
      node_js: '10'

      script:
        - npm run build
        - npm run docs

      deploy:
        # Deploy a new version of NPM package and create a Github release
        - provider: script
          skip_cleanup: true
          script: npx semantic-release

        # Deploy documentation to Github Pages
        # See https://docs.travis-ci.com/user/deployment/pages/
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: built
          on:
            branch: master

    - stage: deploy
      language: python
      python: '3.7'
      dist: xenial

      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        server: https://https://test.pypi.org/legacy/
        on:
          tags: true
