language: node_js
node_js: "10"

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run docs

before_deploy:
  # Copy built files into `public` for deployment of JSON Schema and JSON LD to Github pages
  - mkdir -p public && cp built/* public

deploy:
  # Deploy a new version of NPM package and create a Github release
  - provider: script
    skip_cleanup: true
    script: npx semantic-release

  # Deploy documentation to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: public
    on:
      branch: master
