dist: trusty
sudo: required
matrix:
  include:

    # Typescript latest LTS
    - language: node_js
      node_js: 10

      # Require apt packages
      before_install:
        - sudo apt-get install libsecret-1-dev

      # Do linting, coverage, and build docs (to upload to Github pages)
      script:
        - make lint-ts
        - make cover-ts
        - make build-ts

      # Upload test coverage to codecov
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF ts

      # Prevent Github Pages from using Jekyll
      # (which causes Typedoc generated files starting with undescores to be ignored)
      before_deploy:
        - touch build/.nojekyll

      deploy:
        # Deploy a new version of NPM package and create a Github release
        - provider: script
          skip_cleanup: true
          script:
            - npm run semantic-release

        # Deploy documentation to Github Pages
        # See https://docs.travis-ci.com/user/deployment/pages/
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          local-dir: build
          on:
            branch: master

    # Typescript previous LTS
    - language: node_js
      node_js: 8

      # Just do testing
      script:
        - make test-ts

    # Python latest
    - language: python
      python: "3.7-dev"

      # Install stuff needed for linting and testing
      install:
        - pip3 install pylint mypy tox-travis
      
      # Do linting and coverage
      script:
        - make lint-py
        - make cover-py

      # Upload test coverage to codecov
      after_success:
        - bash <(curl -s https://codecov.io/bash) -cF py

    # Python previous
    - language: python
      python: 3.6

      # Install stuff needed for testing
      install:
        - pip3 install tox-travis
      
      # Just do testing
      script:
        - make test-py

    # R latest
    - language: r
      r: release

      # Packages to install from github using devtools
      r_github_packages:
        - jimhester/lintr
        - klutometis/roxygen2
        - r-lib/covr
        - r-lib/testthat

      # Do linting and coverage
      script:
        - make lint-r
        - make cover-r

    # R previous
    - language: r
      r: oldrel
    
      # Packages to install from github using devtools
      # Just testing
      r_github_packages:
        - r-lib/testthat

      # Just do testing
      script:
        - make test-r
