title: SoftwareApplication
'@id': schema:SoftwareApplication
$extends: ../CreativeWork.schema.yaml
role: primary
status: unstable
description: |
  A software application.
properties:
  softwareRequirements:
    '@id': schema:softwareRequirements
    description: |
      Component dependency requirements for application. This includes runtime environments and shared libraries that are not included in the application distribution package, but required to run the application (Examples: DirectX, Java or .NET runtime).
    type: array
    items:
      - $ref: SoftwareApplication.schema.yaml
  softwareVersion:
    '@id': schema:softwareVersion
    description: Version of the software instance.
    type: string
