title: Environment
'@id': stencila:Environment
extends: Thing
role: primary
status: experimental
category: metadata
description: A computational environment.
properties:
  extends:
    '@id': stencila:extends
    description: Other environments that this environment extends by adding or removing packages.,
    type: array
    items:
      $ref: Environment
  adds:
    '@id': stencila:adds
    description: The packages that this environment adds to the base environments listed under `extends` (if any).,
    type: array
    items:
      $ref: SoftwareSourceCode
  removes:
    '@id': stencila:removes
    description: The packages that this environment removes from the base environments listed under `extends` (if any).,
    type: array
    items:
      $ref: SoftwareSourceCode
  source:
    '@id': stencila:environmentSource
    description: |
      Source of environment definition. e.g. a URL to a Dockerfile,
      or a path to a filesystem folder.
    type: string
required:
  - name
