$schema: http://json-schema.org/draft-07/schema#
$id: https://stencila.github.com/schema/Environment.schema.json
title: Environment
'@id': stencila:Environment
description: A computational environment.
properties:
  extends:
    '@id': stencila:extends
    description: Other environments that this environment extends by adding or removing packages.,
    type: array
    items:
      $ref: Environment.schema.yaml
  adds:
    '@id': stencila:adds
    description: The packages that this environment adds to the base environments listed under `extends` (if any).,
    type: array
    items:
      $ref: Package.schema.yaml
  removes:
    '@id': stencila:removes
    description: The packages that this environment removes from the base environments listed under `extends` (if any).,
    type: array
    items:
      $ref: Package.schema.yaml
  environmentSource:
    '@id': stencila:environmentSource
    description: |
      Source of environment definition. For example, a URL to a Dockerfile, a path to Singularity recipe file,
      or a path to a filesystem folder.,
    allOf:
      - type: string
required:
  - name
