$schema: http://json-schema.org/draft-07/schema#
$id: https://stencila.github.com/schema/Product.schema.json
title: Product
'@id': schema:Product
description: |
  Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; 
  a haircut; or an episode of a TV show streamed online. https://schema.org/Product
allOf:
  - $ref: Thing.schema.yaml
  - brand:
      '@id': schema:brand
      type: object
      items:
        $ref: Brand.schema.yaml
  - productID:
      '@id': schema:productID
      type: string